apiVersion: apps/v1
kind: Deployment
metadata:
 name: taller-facturacion-productos
 labels:
   app: taller-facturacion-productos
spec:
 replicas: 3
 selector:
   matchLabels:
     app: taller-facturacion-productos
 template:
   metadata:
     labels:
       app: taller-facturacion-productos
   spec:
     containers:
       - name: taller-facturacion-productos
         image: acrtallerformativa.azurecr.io/taller-facturacion-productos:0.0.1
         ports:
           - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
 name: taller-facturacion-productos
spec:
 type: LoadBalancer
 ports:
   - port: 80
     targetPort: 80
 selector:
   app: taller-facturacion-productos
